### ISSUE TITLE
Load_model needed

### ISSUE THREAD

**Issue by simonlight** [hugochan/Eye-Tracker#1]
Hi Hugo, I'm interested in studying your work for fun. I wanna first try to run it but I found no loaded model could be passed into the program. Could you please show me how to figure it out? Thx.

**Comment by hugochan** [comment]
Hi,

Thank you for your interest! You should first train your own model on the dataset. I just uploaded a pretrained model, so you can also try loading that model using the itracker_adv.py script.

Hope this helps.

**Comment by simonlight** [comment]
Thank you for your kind help Hugo. But when I ran it, I encountered OOM problem. My GPU is 1080Ti with 11G memory.

**Comment by hugochan** [comment]
@simonlight Current implementation requires large memory space. I previously ran the model using a CPU machine with large RAM, so I did not notice this issue. I will take some time to check if it is possible to reduce memory usage.

**Comment by hugochan** [comment]
@simonlight So here is what we can do. In the training phase, instead of feeding the whole validation set to the model, we can set a smaller batch size. Similarly, in the test phase, set a smaller batch size when feeding the test data to the model. That should fix the issue.

**Comment by pjpjq** [comment]
The same problem. The process got killed after a while, even after trying a smaller batch size...

**Comment by hugochan** [comment]
Hello @wendingp ,

Can you tell me what the batch size you used? It should be fine if you set the test batch size as same as the training batch size.

**Comment by pjpjq** [comment]
I just tested using your pretrained model and didn't train. `python2 itracker_adv.py -i eye_tracker_train_and_val.npz -lm pretrained_models/itracker_adv/model-23  -bs 2` or use batch size 20 didn't work. MacBook Pro CPU temperature got >90 deg cels and after a while the process got killed.

**Comment by hugochan** [comment]
Hello,

To train the model, you need to add --train and -sm (save model path) in your cmd. It doesn't support training a pretrained model.

**Comment by pjpjq** [comment]
No, I don't want to train... I just want to test your pretrained model using your given testing usage...
![image](https://user-images.githubusercontent.com/17057603/42952184-7de9eeb6-8baa-11e8-9d17-a0919962e417.png)

**Comment by hugochan** [comment]
@wendingp Oh, I misunderstood that. In the test phase, the batch size actually does not make any influence. The current implementation feeds the whole validation set to the model at once. You will need to modify the script to support validation batch by batch. Sorry for the inconvenience. May I know the memory space on your MBP? It seems you are running out of memory.

**Comment by pjpjq** [comment]
16G

**Comment by hugochan** [comment]
@wendingp I modified the script to make it support validation batch. Please download the lasted code.

**Comment by pjpjq** [comment]
Same result...

**Comment by hugochan** [comment]
@wendingp I was able to run the test script on my MBP with 8G RAM. Not sure why it didn't work on your machine.

**Comment by pjpjq** [comment]
I try it again and this time it works! With same code... don't know why.
