### ISSUE TITLE
请教下数据集合中y的含义？

### ISSUE THREAD

**Issue by wangshankun** [hugochan/Eye-Tracker#11]
开始以为是坐标，结果发现有正负···知道字段的含义吗？
[[ 1.70154930e+00 -1.93875000e+00]
 [-6.85229867e+00  7.72708985e-01]
 [-1.08925000e+01  5.00000000e-04]
 ...
 [-7.52597535e+00  9.69375000e-01]
 [ 5.78865727e+00 -4.60561372e-01]
 [-3.64302465e+00 -9.69375000e-01]]

**Comment by hugochan** [comment]
y就是二维坐标。

**Comment by CXL-happylearning** [comment]
请问train_y.npy和val_y.npy是只有二维坐标吗？还是包含了前面图像的对应关系？求大神解答，万分感谢！

**Comment by hugochan** [comment]
@CXL-happylearning 包含left eye, right eye, face, face mask图像以及eye gaze 坐标。
