### ISSUE TITLE
python code to extract face, left eye, right eye and face grid from multiple images 

### ISSUE THREAD

**Issue by lii08** [hugochan/Eye-Tracker#12]
Hi, really appreciate if you could provide and share the python code to extract face, left eye, right eye and face grid from multiple images (or video / sequence of image frame). In short image.jpg to face.npy, LeftEye.npy, RightEye.npy and FaceGrids.npy. (or .npz file)

**Comment by hugochan** [comment]
Hi @lii08 , I actually do not have the code. I used a dataset shared by someone else. You might want to turn to the original authors for help. Good luck!
