### ISSUE TITLE
关于标签y

### ISSUE THREAD

**Issue by CXL-happylearning** [hugochan/Eye-Tracker#14]
你好，请问train_y.npy、val_y.npy文件里只是单纯的（x,y）坐标，还是包含了前面四个图像输入的对应关系？求大神解答

**Comment by CXL-happylearning** [comment]
另外还想问下，以上（x,y）坐标是写入txt文件，然后转成npy格式吗？如果是数字标签，是否可以做同样操作？在网络中应该做怎样的修改？求大神解答

**Comment by hugochan** [comment]
@CXL-happylearning 包含left eye, right eye, face, face mask图像以及eye gaze 坐标。npy格式可以存储矩阵字典，使用numpy.save和numpy.load函数。
