### ISSUE TITLE
What is train_y and val_y in dataset?

### ISSUE THREAD

**Issue by IvanKwokKC** [hugochan/Eye-Tracker#15]
I expect both train_y and val_y are the 2D coordination of eye graze .

But the result is quite strange. Most of the coordination are very small or negative. That means most eye graze always point at the left top side. But the fact doesn't like that. Most of them are wrong.

![Capture000](https://user-images.githubusercontent.com/39858630/58377807-5d279d80-7fbb-11e9-9905-104f8bc77327.PNG)

Please concern the circle and the center of circle. The center is the predicted point of eye gaze.

![Capture001](https://user-images.githubusercontent.com/39858630/58377835-05d5fd00-7fbc-11e9-8524-0c66519e4aca.PNG)
![Capture002](https://user-images.githubusercontent.com/39858630/58377837-0a021a80-7fbc-11e9-9c11-5aae008dca62.PNG)

**Comment by hugochan** [comment]
@IvanKwokKC It's because the input data has been normalized. You may want to check out the official release of the code [here](https://github.com/CSAILVision/GazeCapture).

**Comment by IvanKwokKC** [comment]
I find the normalization function in the code:

```
def normalize(data):
    shape = data.shape
    data = np.reshape(data, (shape[0], -1))
    data = data.astype('float32') / 255. # scaling
    data = data - np.mean(data, axis=0) # normalizing
return np.reshape(data, shape)
```

I am not good in statistics. I think this is zero mean normalization.
`data = data - np.mean(data, axis=0) # normalizing`

Does it possible convert normalized data back to original one?
I have no idea.

**Comment by hugochan** [comment]
@IvanKwokKC I think you can just keep the original data.

**Comment by Vampire-Vx** [comment]
I think the output is strange. The input has been normalized using a zero-mean function. However, the output always stay a small or negative number.

**Comment by Vampire-Vx** [comment]
train_y and val_y is actually the xy offset from your mobile phones camera. According to this dataset, the offset ranges from 0~20 centimeters. You normalize the input data but your did not normalize the output of the network. The problem is not the normalization.

**Comment by hugochan** [comment]
@Vampire-Vx Thank you for providing additional information. I wondered if the output has already been normalized by the original authors when releasing the dataset. The dataset I was using was a small sampling from the whole dataset. Please refer to #4 for more about this dataset. You may want to contact the original authors to get the raw output.
