### ISSUE TITLE
你好，请问facemask在预测的时候传入的是什么格式的？比如其它特征是64x64的矩阵格式。多谢博主

### ISSUE THREAD

**Issue by Ar4enal** [hugochan/Eye-Tracker#16]

**Comment by hugochan** [comment]
@Ar4enal face_mask: 25 x 25 binary matrix.

**Comment by Ar4enal** [comment]
@hugochan 谢谢博主。

还有一个问题，就是在预测时feed_dict里传入参数的时候提示我还需要传入pos的数据，但是这是我要预测的坐标，请问怎么更改代码能得出预测的gaze坐标？或者我这个是错的？十分感谢(*^▽^*)

a = graph.get_tensor_by_name("eye_left:0")
b = graph.get_tensor_by_name("eye_right:0")
c = graph.get_tensor_by_name("face:0")
d = graph.get_tensor_by_name("face_mask:0")
e = graph.get_tensor_by_name("pos:0")
......
feed_dict = {a:left_eye, b:right_eye, c:face, d:face_grid}
res = sess.run(e,feed_dict)

**Comment by hugochan** [comment]
@Ar4enal 
` eye_left, eye_right, face, face_mask, pred = val_ops`
` pred_pos = session.run(pred, feed_dict={eye_left: batch_val_data[0],   eye_right: batch_val_data[1], face: batch_val_data[2],  face_mask: batch_val_data[3]})`

请参考[validate_model 函数](https://github.com/hugochan/Eye-Tracker/blob/master/itracker_adv.py#L351)

**Comment by Ar4enal** [comment]
@hugochan 因为我预测的是一张图片jpg格式，而不是文中的val_ops，请问pred怎么初始化？其它四个参数我已经处理好了

#pred = graph.get_tensor_by_name("Add_5:0")
#pred = graph.get_tensor_by_name("Variable_13:0")
我试了这几个，但是结果都是有正有负的，类似如下
[array([ 0.14147238, -0.20125845], dtype=float32)]

怎么能得出预测的x，y坐标呢？多谢博主

**Comment by hugochan** [comment]
@Ar4enal 你可以参考[这里](https://github.com/hugochan/Eye-Tracker/blob/master/itracker_adv.py#L84)，做一个反过程，把network output转化为实际坐标。

**Comment by Ar4enal** [comment]
@hugochan 好的，谢谢，我已经解决了
