### ISSUE TITLE
How i can train the dataset  

### ISSUE THREAD

**Issue by zeyadyemeni** [hugochan/Eye-Tracker#17]
I am trying to run this in cmd but there is an error 

python itracker_adv.py --train -i input_data -sm saved_model

how I can give the path of the dataset 

def load_data(file):
    npzfile = np.load(file)

thank you

**Comment by hugochan** [comment]
> I am trying to run this in cmd but there is an error
> 
> python itracker_adv.py --train -i input_data -sm saved_model
> 
> how I can give the path of the dataset
> 
> def load_data(file):
> npzfile = np.load(file)
> 
> thank you

Thank you for your interest to the work! You can find the link to the dataset following the FQA section in the README page.
