### ISSUE TITLE
What is the tensorflow version required for this Eye-Tracker

### ISSUE THREAD

**Issue by codhao** [hugochan/Eye-Tracker#18]
Have been using Tensorflow 2.0 but I realized i had multiple issues calling functions like tf.session()

**Comment by hugochan** [comment]
> Have been using Tensorflow 2.0 but I realized i had multiple issues calling functions like tf.session()

@njh18 Thank you for your interest to this project! This project was written 3 years ago. I think the code was probably written with TensorFlow 1.5 or so. You might need to modify the code a bit in order to run it with TensorFlow 2.

**Comment by codhao** [comment]
@hugochan Thank you for your reply! Can i check whats the command statement required to run the pretrained data?

**Comment by hugochan** [comment]
> @hugochan Thank you for your reply! Can i check whats the command statement required to run the pretrained data?

To train the model: run python itracker_adv.py --train -i input_data -sm saved_model

To test the trained model: run python itracker_adv.py -i input_data -lm saved_model

You can find a pretrained (on the smaller dataset) model under the pretrained_models/itracker_adv/ folder.
