### ISSUE TITLE
How does one specify device type and orientation?

### ISSUE THREAD

**Issue by abhinavvadrevu** [hugochan/Eye-Tracker#2]
Hi, I remember reading this paper some time back, and as I understand the device type and orientation mattered a lot. This is because the position of the camera relative to the screen makes a difference.

In this code, I don't see any parameters to specify device type or orientation. Wondering if you could please explain what I'm missing? Does this model only work for a specific device type and orientation? Which device and orientation would that be?

Thanks in advance!

**Comment by hugochan** [comment]
@abhinavvadrevu What you suggested is an interesting point. However, I don't think that paper considered either device type or orientation and there is no such information in the dataset. I suggest you to talk to the authors of the paper for more information.

**Comment by abhinavvadrevu** [comment]
Ah, thanks @hugochan! Another quick question: The paper used 224x224 images for the face and eyes, but your implementation is 64x64. Did you compress the original dataset and find that accuracy was not affected?

**Comment by hugochan** [comment]
@abhinavvadrevu Due to the limitation of computation power, a much smaller dataset was used. You can download the original dataset [here](https://github.com/CSAILVision/GazeCapture).

**Comment by abhinavvadrevu** [comment]
Ah, gotcha. I thought you meant fewer samples when you said "smaller dataset" in the README - not smaller images.

So have you found that the performance is significantly worse with smaller images?  I ask because I'm considering retraining with the original dataset (I'll only do it if there's a significant performance boost in doing that!)

**Comment by hugochan** [comment]
@abhinavvadrevu Sorry, I don't have the comparison results. But it is worth a try.

**Comment by abhinavvadrevu** [comment]
No worries, I'll let you know what I find!
