### ISSUE TITLE
Capturing face parts

### ISSUE THREAD

**Issue by pablocastilla** [hugochan/Eye-Tracker#3]
Hi!

Do you know a good method for capturing the face parts from a video or a image?

Thanks

**Comment by hugochan** [comment]
Hi,

There should be some image segmentation methods for capturing the face parts. However, I don't know any particular one. So I cannot recommend any to you. Sorry.

**Comment by rewari14** [comment]
https://www.pyimagesearch.com/2017/04/10/detect-eyes-nose-lips-jaw-dlib-opencv-python/
