### ISSUE TITLE
Training on Custom Dataset

### ISSUE THREAD

**Issue by abhigoku10** [hugochan/Eye-Tracker#5]
@hugochan  hi thanks for the wonderful code for eye tracking and detection , just wanted to know whats the procedure to train on a custom dataset? can you briefly give the pointers for training on the new/ custom dataset

**Comment by hugochan** [comment]
Hi,

Thank you for your attention! I'm just not quite sure what the custom dataset here refers to. Were you talking about the smaller dataset I used for training the model? If so, it's just for reducing computational cost. Nothing else. It would be even better if you can train the model on the whole dataset as done in the original paper.

**Comment by abhigoku10** [comment]
@hugochan  i downloaded the smaller dataset but i keep getting any output as **Total valid frames: 0**
 and no files are created in the output folder. can you elaborate the procedure to use this smaller dataset

**Comment by hugochan** [comment]
Hi @abhigoku10, to train the model, run this: `python itracker_adv.py --train -i input_data -sm saved_model`. To test the trained model, run this: `python itracker_adv.py -i input_data -lm saved_model`.  I don't know why no files were created. Did you see any message like _Model saved in file..._?

**Comment by abhigoku10** [comment]
@hugochan  no i did not see any msg , later when i wend thru the code the path to save the weights was not absolute path so now i am able to save the weights
