### ISSUE TITLE
about the better prediction error

### ISSUE THREAD

**Issue by amdgigabyte** [hugochan/Eye-Tracker#6]
Hi, Hugo Chan, nice to meet you, I am recently focused on this technology which might help us to get to know more about our end-user's thoughts, I read about the MIT paper, they claim their prediction error is 1.71cm on mobile and 2.53cm on a tablet. 

And in this repo's README, it says" better validation error (2.19 cm vs. 2.514 cm)", is this the comparison to the MIT <eye_tracking_for_everyone> result?

Thanks!

**Comment by hugochan** [comment]
Hello @amdgigabyte , the validation errors mentioned in README are on the [smaller dataset](http://hugochan.net/download/eye_tracker_train_and_val.npz) instead of the origin dataset used in the paper.

**Comment by amdgigabyte** [comment]
@hugochan so, the result 2.19cm is on mobile or on a tablet?

**Comment by hugochan** [comment]
@amdgigabyte Since I am not the person who created this smaller dataset, I am not 100% sure. BTW, just found the official repo was made public, you might want to check out [this](https://github.com/CSAILVision/GazeCapture).

**Comment by amdgigabyte** [comment]
I had already checked out the original repo. But at present, the original dataset cannot be downloaded, so I have to find other datasets. 
o(╥﹏╥)o
