### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by mranosa** [hugochan/Eye-Tracker#9]
Hello, I dont have an ML background, but would like to try this out.

How do I get the x and y gaze prediction output, given a face image, width and height of screen and maybe some camera details (distance of camera to screen, and camera size maybe)?

An example python implementation would be great, thanks a lot :D

Cheers!

P.S. Can this be used to for different screen size? like instead of an iPhone screen, a 24 inch monitor is used?

**Comment by hugochan** [comment]
Hi @mranosa, I am not sure if I really understand your 1st question. If you are asking for a conceptual explanation on why this model will work, I would recommend you to read [their paper](https://arxiv.org/abs/1606.05814). 

As for the 2nd question, yes, you can use this model for a different screen size. But you will need to train the model on the corresponding dataset.
